# name: DigitalOcean App Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   digitalocean_app_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: DigitalOcean App Deployment Action
#         uses: rdarida/digitalocean-app-deployment-action@v1.0.2
#         with:
#           token: ${{ secrets.DIGITALOCEAN_TOKEN }}
#           appId: ${{ secrets.DIGITALOCEAN_APPID }}